version: '3'

services:

  flaskapp:

    build: .

    container_name: flaskapp

    ports:
      - "5000:5000"

    restart: always

  prometheus:

    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    restart: always

  grafana:

    image: grafana/grafana

    container_name: grafana

    ports:
      - "3000:3000"

    restart: always
    
  node-exporter:

    image: prom/node-exporter

    container_name: node-exporter

    ports:
      - "9100:9100"

    restart: always  
  nginx:

    image: nginx

    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - flaskapp

    restart: always 
    
  loki:

    image: grafana/loki

    container_name: loki

    ports:
      - "3100:3100"

    volumes:
      - ./loki/config.yml:/etc/loki/config.yml

    command: -config.file=/etc/loki/config.yml

    restart: always  