name: Auto Deploy Flask App

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}

        script: |
          sudo docker stop mycontainer || true
          sudo docker rm mycontainer || true

          rm -rf /home/ubuntu/project

          cd /home/ubuntu

          git clone https://github.com/aviteshs/project.git

          cd /home/ubuntu/project

          sudo docker build --no-cache -t myapp .

          sudo docker run -d -p 5000:5000 --name mycontainer myapp